first_committee_to_number = {
  "Medical Peer Review Process, Interim": 0,
  "Border Affairs, Special": 1,
  "Local Government": 2,
  "Environment, Interim": 3,
  "Election Contest District 58, Select": 4,
  "Child Protective Services, Special": 5,
  "International and Cultural Relations": 6,
  "TRS-Care, House Joint": 7,
  "Transportation Financing": 8,
  "SB 97, Select": 9,
  "Business and Commerce": 10,
  "Finance Subcommittee on General Government Issues": 11,
  "Technology, Economic Development, and Workforce": 12,
  "Administration, Special": 13,
  "Practice of Breeding White-tailed and Mule Deer, Select Interim": 14,
  "Jurisprudence": 15,
  "NAFTA and GATT, Special Select": 16,
  "Fiscal Impact of Texas Border Support Operations, Select": 17,
  "Appropriations Subcommittee on Duplication of Services": 18,
  "Guardianship": 19,
  "Transportation, Interim": 20,
  "Finance Subcommittee on Higher Education": 21,
  "Appropriations Subcommittee on Education": 22,
  "Open Government, Select": 23,
  "Committee of the Whole on Redistricting, Special, Subcommittee on Legislative Districts": 24,
  "Texas Health Insurance Risk Pool Deficit, Interim": 25,
  "Finance Subcommittee on Medicaid": 26,
  "Seacoast Territory Insurance": 27,
  "Public Education": 28,
  "Recruitment of Firearms and Ammunition Manufacturers": 29,
  "Redistricting Subcommittee on Congressional Redistricting One": 30,
  "Resolutions Calendars": 31,
  "Creation and Expansion of Minority and Women-Owned Business Ownership Opportunities, Special Advisory": 32,
  "Finance Subcommittee on Public Safety": 33,
  "Land Purchases of the University of Texas, Investigate": 34,
  "Appropriations Subcommittee on State Infrastructure, Resiliency, and Investment": 35,
  "The Robb Elementary Shooting, Investigative": 36,
  "County Affairs": 37,
  "Private Participation in Toll Projects, Legislative Study": 38,
  "Finance Subcommittee on Veteran Affairs": 39,
  "Investments and Financial Services": 40,
  "Public Safety Subcommittee on Budget And Oversight": 41,
  "Cultural and Historical Resources": 42,
  "Natural Resources Subcommittee on Agriculture and Coastal Resources": 43,
  "Water Desalination": 44,
  "Nominations": 45,
  "Calendars": 46,
  "Veteran Affairs and Military Installations Subcommittee on Base Realignment and Closure": 47,
  "Fiscal Stability, Select": 48,
  "Appropriations Subcommittee on Health and Human Services": 49,
  "Environmental Regulation": 50,
  "Employment Practices, Select": 51,
  "Veterans' Affairs, Special": 52,
  "Tilt-rotor Technology, Task Force on": 53,
  "Border and International Affairs": 54,
  "General Investigating, Special": 55,
  "Child Protection, Select": 56,
  "Administration": 57,
  "Pensions and Investments": 58,
  "Human Services Subcommittee on Budget and Oversight": 59,
  "Community-Based Care Transition, Oversight": 60,
  "Committee of the Whole on Redistricting, Special, Subcommittee on Congressional Districts": 61,
  "Finance Subcommittee I": 62,
  "Criminal Defendant's Competency, Task Force": 63,
  "Construction Industry-Related Workers' Compensation Issues, Select, Interim": 64,
  "Statewide Health Care Costs, Select": 65,
  "Natural Resources Subcommittee on Agriculture": 66,
  "State, Federal and International Relations": 67,
  "Availability of Pre-Owned Heavy Duty Commercial Motor Vehicles, Study Commission on": 68,
  "Liquor Regulation": 69,
  "Appropriations Subcommittee on Health and Human Services (Article II)": 70,
  "Appropriations Subcommittee on Environmental and General Government": 71,
  "Development Over Closed Landfills, Special": 72,
  "State Employee Compensation and Benefits, Special": 73,
  "Criminal Justice Reform, Interim Study": 74,
  "Texas Catastrophic Property Insurance Pool, Special": 75,
  "Appropriations Subcommittee on General Government": 76,
  "Family Code, Interim": 77,
  "International Relations, Trade, and Technology": 78,
  "SB 19, Select": 79,
  "Transportation Funding, Expenditures, and Finance, Select": 80,
  "Higher Education, Select": 81,
  "Juvenile Justice and Family Issues": 82,
  "Nominations, Special": 83,
  "Ways and Means Subcommittee on Budget and Oversight": 84,
  "Violence in Schools & School Security, Select": 85,
  "Economic Competitiveness, Select": 86,
  "Senate Chamber Review": 87,
  "Public School Finance, Select Subcommittee on Cost Adjustments": 88,
  "Public School Finance, Texas Commission on": 89,
  "Property Tax Relief, Select": 90,
  "Science and Technology Subcommittee on Budget and Oversight": 91,
  "Appropriations Subcommittee on Articles VI, VII, and VIII (Natural Resources, Business and Economic Development, and Regulatory)": 92,
  "Agriculture, Water, and Rural Affairs": 93,
  "Appropriations Subcommittee on Budget and Oversight": 94,
  "Government Facilities, Select": 95,
  "Low-Level Radioactive Waste Disposal Compact Facility Legislative Oversight": 96,
  "Public Safety Subcommittee on Oversight": 97,
  "Appropriations Subcommittee on Criminal Justice (Articles IV and V)": 98,
  "Redistricting Subcommittee on Congressional Redistricting Two": 99,
  "Ethics, Select": 100,
  "Statewide Media Task Force on Dropout Prevention": 101,
  "Economic Development, Select": 102,
  "State Affairs Subcommittee on Elections": 103,
  "Judicial Affairs Subcommittee on Budget and Oversight": 104,
  "Higher Education, Interim": 105,
  "Mass Violence Prevention and Community Safety, Select": 106,
  "Natural Resources and Economic Development Subcommittee": 107,
  "Agriculture and Livestock Subcommittee on Budget and Oversight": 108,
  "Texas Infrastructure Resiliency Fund Advisory": 109,
  "Rules and Resolutions": 110,
  "State Affairs Subcommittee on Infrastructure": 111,
  "Health and Human Services Eligibility System, Oversight": 112,
  "Property and Casualty Insurance, Legislative Oversight": 113,
  "Government Reform": 114,
  "Education Policy for a Skilled Workforce": 115,
  "Electric Utility Restructuring, Interim": 116,
  "Border and Intergovernmental Affairs": 117,
  "State Health Care Expenditures, Select": 118,
  "Pensions, Investments, and Financial Services": 119,
  "Science and Technology": 120,
  "Election Contest District 129, Special": 121,
  "Gangs and Juvenile Justice, Interim": 122,
  "Veterans Health, Select": 123,
  "Public School Finance, Select Subcommittee on Alternative Delivery Methods": 124,
  "Texas Lottery and Texas Lottery Commission": 125,
  "Appropriations Subcommittee on Education (Article III)": 126,
  "Economic Development Incentives, Select": 127,
  "Appropriations Subcommittee on Regulatory (Article VIII)": 128,
  "Constitutional Revision, Select": 129,
  "Election Security, Select": 130,
  "Appropriations Subcommittee on the Current Fiscal Condition": 131,
  "Property Tax Reform, Select": 132,
  "Legislative and Congressional Redistricting, Committee of the Whole Senate, Special": 133,
  "Finance Subcommittee on Capital Funding for Higher Education": 134,
  "Government Transparency and Operation": 135,
  "State Judicial Salaries": 136,
  "General Investigating and Ethics": 137,
  "Intergovernmental Relations Subcommittee on Flooding and Evacuations": 138,
  "International Relations, Trade and Technology": 139,
  "Veteran Affairs and Border Security": 140,
  "Federal Economic Stabilization Funding, Select": 141,
  "Finance, Interim": 142,
  "Investments and Financial Services Subcommittee on Bond Indebtedness": 143,
  "Partnership Advisory Commission": 144,
  "Transportation and Homeland Security": 145,
  "Texas State Artist": 146,
  "Rules, Select": 147,
  "General Investigating": 148,
  "Appropriations Subcommittee on Emoluments": 149,
  "Education, Interim": 150,
  "Revenue and Public Education Funding, Select": 151,
  "Constitutional Issues, Special": 152,
  "Housing, Interim": 153,
  "Child Welfare and Foster Care, Select, Interim": 154,
  "Opioids and Substance Abuse, Select": 155,
  "Investments and Banking": 156,
  "Youth Health and Safety, Select": 157,
  "Public School Facilities, Interim": 158,
  "Waste Management Policy, Task Force on": 159,
  "State Real Property Data Collection, Reporting, and Assessment, Select": 160,
  "Bexar Metropolitan Water District, Oversight": 161,
  "Nursing Home Rate Reimbursement, Interim": 162,
  "Economic Development Subcommittee on Public-Private Partnerships": 163,
  "Public Education Subcommittee on Oversight": 164,
  "Transportation Planning, Select": 165,
  "Environmental Affairs": 166,
  "Elections Subcommittee on Budget and Oversight": 167,
  "Health and Human Services": 168,
  "Financial Institutions": 169,
  "Health and Human Services Block Grants, House Joint": 170,
  "Alzheimer's Disease": 171,
  "Electric Generation Capacity and Environmental Effects, Select": 172,
  "Appropriations Subcommittee on Criminal Justice": 173,
  "Jurisprudence, Interim": 174,
  "Education Reform and Public School Finance, Select": 175,
  "Human Services": 176,
  "Health Insurance Access, Interim": 177,
  "Human Trafficking": 178,
  "Natural Resources and Economic Development": 179,
  "Texas Ports, Select": 180,
  "Electric Utility Restructuring, Special": 181,
  "Insurance Regulation, Special": 182,
  "Home Health and Assisted Living Facilities, Interim": 183,
  "Border Security": 184,
  "Finance Subcommittee III": 185,
  "Judicial Selection": 186,
  "Redistricting, Ethics and Elections, Committee of the Whole Senate, Subcommittee on Elections and Ethics, Standing": 187,
  "Property Tax Reform and Relief, Select": 188,
  "Committee of the Whole on Redistricting, Special": 189,
  "Appropriations Subcommittee on Articles I, IV, and V (General Government, the Judiciary, and Criminal Justice and Public Safety)": 190,
  "Dyslexia and Related Disorders, Interim": 191,
  "Legislative Redistricting, Select": 192,
  "Health Services": 193,
  "Economic Development Subcommittee on Insurance": 194,
  "State Bond Revenues, Select": 195,
  "Transparency in State Agency Operations, Select": 196,
  "Finance Subcommittee on Property Appraisal and Revenue Caps": 197,
  "Higher Education Subcommittee on Budget and Oversight": 198,
  "Public Utility Commission, Interim": 199,
  "State Artist, Select": 200,
  "Government Facilities": 201,
  "Redistricting, Ethics and Elections, Committee of the Whole Senate, Special": 202,
  "Criminal Commitments of Individuals with Mental Retardation, Interim Select": 203,
  "Education Subcommittee on Higher Education": 204,
  "Workers' Compensation Insurance Policies, Special": 205,
  "Economic Development Subcommittee on Technology and Business Growth": 206,
  "Public Education Reform, Select": 207,
  "Intergovernmental Relations": 208,
  "Elections": 209,
  "Emissions and Clean Air, Special": 210,
  "Higher Education Governance, Excellence, and Transparency, Select Oversight": 211,
  "Appropriations Subcommittee on Article II (Health and Human Services) ": 212,
  "Government Efficiency, Interim": 213,
  "Sex Offenders, Interim": 214,
  "Appropriations Subcommittee on Regulatory Agencies": 215,
  "Criminal Justice and People with Mental Disabilities, House Joint": 216,
  "Veteran Affairs and Military Installations": 217,
  "State Water Implementation Fund for Texas Advisory": 218,
  "Statutory Probate Courts Jurisdiction, Interim": 219,
  "Public School Finance, Select": 220,
  "Local and Consent Calendars": 221,
  "Higher Education Formula Funding": 222,
  "Civil Practices": 223,
  "Rock Crushers and Quarries, Advisory": 224,
  "Driver's License Issuance and Renewal, Select": 225,
  "Electric Utility Restructuring, Legislative Oversight": 226,
  "Economic Stabilization Fund Balance, Select": 227,
  "Transportation Funding, Select": 228,
  "Appropriations Subcommittee on Hurricane": 229,
  "Edwards Aquifer, Special": 230,
  "Auto Theft and Uninsured Motorists, Special": 231,
  "Legislative and Congressional Redistricting, Committee of the Whole Senate": 232,
  "Infrastructure Development and Security": 233,
  "Military and Veterans Affairs, Select": 234,
  "Long-Term Care, Legislative Oversight": 235,
  "Workforce Development, Legislative Oversight": 236,
  "Criminal Justice, Oversight": 237,
  "State Investment Policy, House Joint": 238,
  "Juvenile Driving While Intoxicated Laws, Interim": 239,
  "Return-to-Work, House Joint": 240,
  "Redistricting, Special": 241,
  "Homeland Security and Public Safety": 242,
  "Higher Education Subcommittee on Post-Secondary and Workforce Readiness": 243,
  "Economic and Small Business Development Subcommittee on Small Business": 244,
  "Appropriations Subcommittee on Stimulus": 245,
  "Pensions": 246,
  "Comptroller Sharp's Texas Performance Review of the Texas Department of Criminal Justice, Interim": 247,
  "Tax Reform and Public School Finance, Select": 248,
  "Appropriations Subcommittee on Government Efficiency and Operations": 249,
  "Labor and Employment Relations": 250,
  "Public Education Subcommittee on Budget and Oversight": 251,
  "Public School Finance, Select Subcommittee on Benefits/Compensation": 252,
  "Job Training Partnership Act Monitoring": 253,
  "Veteran Affairs and Military Installations, Special": 254,
  "Urban Affairs": 255,
  "Dental Practice Act, Select": 256,
  "Telecommunications, Interim": 257,
  "Advisory Council on the Digital Economy": 258,
  "Public Health": 259,
  "Regional Issues, House Joint": 260,
  "Appropriations Subcommittee on Dedicated Funds": 261,
  "Federal Legislation, Select": 262,
  "Committee of the Whole Senate ": 263,
  "Finance Subcommittee on Higher Education Funding": 264,
  "Property Tax": 265,
  "Appropriations Subcommittee on Strategic Fiscal Review and Federal Relief Funds": 266,
  "Juvenile Justice and Child Support, Interim": 267,
  "Prescribing and Dispensing Controlled Substances": 268,
  "Energy": 269,
  "Natural Resources Subcommittee on Budget and Oversight": 270,
  "Oil Spills and Water Pollution Abatement": 271,
  "Prompt Payment of Health Care Providers, Special": 272,
  "Texas Ports, Innovation and Infrastructure, Select": 273,
  "Open Government": 274,
  "Voter Identification and Voter Fraud, Select": 275,
  "Public School Finance, Select Subcommittee on Tax": 276,
  "Erect a Memorial for Korean and Vietnam Veterans": 277,
  "International Trade and Intergovernmental Affairs": 278,
  "Annexation, Interim": 279,
  "Water Policy, Select, Subcommittee on Lease of State Water Rights": 280,
  "Election Contests, Select": 281,
  "State Sovereignty, Select": 282,
  "Public School Finance, Select Subcommittee on Completion and Dropout Rates": 283,
  "Windstorm Insurance, Oversight": 284,
  "Technology": 285,
  "Public Health Subcommittee on Budget and Oversight": 286,
  "Ethics Laws, Select": 287,
  "Power of Eminent Domain, Interim": 288,
  "Petroleum Storage Tanks, Interim": 289,
  "Historically Underutilized Businesses, Select": 290,
  "Municipal Franchise Agreements for Telecommunications Utilities": 291,
  "Qualified Providers, Interim": 292,
  "State and Federal Power and Responsibility, Select": 293,
  "Texas Environmental Flows Advisory Group": 294,
  "Finance Subcommittee on State and Local Revenue Matters": 295,
  "Higher Education Excellence Funding, Interim": 296,
  "Higher Education": 297,
  "Education Subcommittee on School Dropouts": 298,
  "Special Purpose Districts": 299,
  "Toxic Air Emissions and Greenhouse Effect, Select": 300,
  "Public School Finance, Select Subcommittee on Governance": 301,
  "Appropriations Subcommittee on Tobacco": 302,
  "Government Organization": 303,
  "Veteran Affairs": 304,
  "Retirement and Aging Subcommittee on Budget and Oversight": 305,
  "Agriculture Policy": 306,
  "Regulated Industries": 307,
  "Public School Finance, Select Subcommittee on Incentives/Accountability": 308,
  "Appropriations Subcommittee on Public Safety Corrections and Judicial": 309,
  "Ports, Select": 310,
  "Water For Environmental Flows": 311,
  "Services for Individuals Eligible for Intermediate Care Facility Services, Select": 312,
  "Appropriations Subcommittee on Article II (Health and Human Services)": 313,
  "Redistricting": 314,
  "Committee of the Whole Senate": 315,
  "Constitutional Rights and Remedies, Select": 316,
  "Economic and Small Business Development Subcommittee on Manufacturing": 317,
  "Proprietary Schools, Interim": 318,
  "Business and Industry": 319,
  "Higher Education, Legislative Oversight": 320,
  "Human Services Subcommittee on Integrated Eligibility and TIERS Implementation": 321,
  "Public Information, Interim": 322,
  "Public Education, Select": 323,
  "Agriculture and Wildlife Management": 324,
  "Investment in Information Technology Improvement and Modernization Projects, Oversight": 325,
  "Rural Development, Select": 326,
  "Managed Care and Consumer Protections, Interim": 327,
  "Appropriations Subcommittee on Regulatory": 328,
  "Mandated Health Benefits, Interim": 329,
  "Hopwood, and State Contract and Employment Practices, Special": 330,
  "Transportation Subcommittee on Budget and Oversight": 331,
  "Employee Benefits, Select": 332,
  "Domestic Violence, Interim": 333,
  "Texas Integrated Enrollment Services, Legislative Oversight ": 334,
  "Medicaid Reform, Legislative Oversight": 335,
  "Cruise Industry Development": 336,
  "Health Care Reform, Select": 337,
  "Natural Resources Subcommittee on Water": 338,
  "Environmental Regulation Subcommittee on Oversight": 339,
  "Corrections": 340,
  "Economic and Small Business Development": 341,
  "Future of College Sports in Texas, Select": 342,
  "International Relations and Trade": 343,
  "Redistricting, Select": 344,
  "Public School Finance Weights, Allotments, and Adjustments, Select": 345,
  "Environmental Affairs Subcommittee on Budget and Oversight": 346,
  "Judiciary": 347,
  "Economic Development": 348,
  "Transportation Subcommittee on Long-term Infrastructure Planning": 349,
  "Use of Prior Authorization and Utilization Review Processes": 350,
  "TNRCC Funding, House Joint": 351,
  "Defense Affairs and State-Federal Relations": 352,
  "Higher and Public Education Finance, Select": 353,
  "Property Tax Relief and Appraisal Reform, Select": 354,
  "Natural Resources, Interim": 355,
  "Private Activity Bonds, Interim": 356,
  "Judicial Selection, Interim": 357,
  "Criminal Procedure Reform, Select": 358,
  "Federalism and Fiscal Responsibility, Select": 359,
  "Health Care Education and Training, Select": 360,
  "State Affairs": 361,
  "Initiative and Referendum, Interim": 362,
  "Appropriations Subcommittee on Article IX": 363,
  "Health and Human Services, Interim": 364,
  "Disclosure of Emergency Call Information": 365,
  "Health and Human Services, Select": 366,
  "Public Safety Subcommittee on Budget and Oversight": 367,
  "State Affairs, Interim Subcommitee on Workforce Development": 368,
  "Aggregate Production Operations, Interim Study": 369,
  "Business and Commerce Subcommittee on Budget and Oversight": 370,
  "Texas Agricultural Extension Service, House Joint": 371,
  "North American Free Trade Agreement, Interim": 372,
  "Liquor Regulation Subcommittee on Budget and Oversight": 373,
  "Government Efficiency and Accountability, Select": 374,
  "Finance Subcommittee on Articles VI and VII": 375,
  "Mental Health, Select": 376,
  "Affordable Housing, House Joint": 377,
  "Bishop College, Special Advisory": 378,
  "Energy Subcommittee on Budget and Oversight": 379,
  "Retirement and Aging": 380,
  "Laredo State University": 381,
  "Public Education Subcommittee on Educator Quality": 382,
  "Licensing and Administrative Procedures": 383,
  "House Research Organization Steering Committee": 384,
  "Appropriations Subcommittee on Article III (Public and Higher Education)": 385,
  "Judicial Interpretations of Law, Select": 386,
  "Border Wait Times": 387,
  "TEXAS and Teach for Texas Grant Programs, Legislative Oversight": 388,
  "Use of Sales Tax on Sporting Goods, Legislative Task Force": 389,
  "State Recreational Resources": 390,
  "Sex Offender Statutes, Select, Interim": 391,
  "Poet Laureate": 392,
  "Education": 393,
  "Blue Ribbon Task Force on the Uninsured": 394,
  "Agriculture and Livestock": 395,
  "Business and Commerce Subcommittee on Border Affairs": 396,
  "Redistricting Subcommittee on Congressional Redistricting Three": 397,
  "Natural Resources Subcommittee on Agriculture, Rural Affairs & Coastal Resources": 398,
  "Texas Quarter Dollar Coin Design Advisory": 399,
  "Transportation": 400,
  "Insurance": 401,
  "Medicaid Reform Waiver, Legislative Oversight": 402,
  "Coastal Barrier System": 403,
  "Public School Accountability, Select": 404,
  "Home Equity Lending, Interim": 405,
  "Health and Human Services Transition, Legislative Oversight": 406,
  "Health and Human Services Subcommittee on Health Services": 407,
  "State Affairs Subcommittee on Elections and Ethics": 408,
  "Texas State Technical Institute": 409,
  "Appropriations Subcommittee on Budget Transparency and Reform": 410,
  "Culture, Recreation, and Tourism": 411,
  "Finance Subcommittee on Public Education Funding": 412,
  "Appropriations Subcommittee on Business and Economic Development": 413,
  "Energy Resources": 414,
  "Finance Subcommittee II": 415,
  "Emergency Preparedness, Select": 416,
  "Finance Subcommittee on Fiscal Matters": 417,
  "Redistricting, Ethics and Elections, Committee of the Whole Senate, Special Subcommittee": 418,
  "General Revenue Dedicated Accounts, Interim": 419,
  "Agriculture & Rural Affairs": 420,
  "Election Contest District 144, Special": 421,
  "Review of the Central Education Agency, Select": 422,
  "Transportation Funding, Select, Subcommittee on Planning & Accountability": 423,
  "Natural Resources Subcommittee on Special Water Districts": 424,
  "TRS Health Benefit Plans": 425,
  "Transportation Funding, Select, Subcommittee on Funding": 426,
  "Criminal Jurisprudence": 427,
  "Cultural and Historical Resources Subcommittee on Budget and Oversight": 428,
  "Defense and Veterans' Affairs": 429,
  "Health and Long-Term Care Insurance Incentives": 430,
  "Finance": 431,
  "Financial Institutions Subcommittee on Budget and Oversight": 432,
  "Rural Transportation Infrastructure, Interim": 433,
  "Uniform Jury Handbook, Legislative Oversight": 434,
  "Small Business Access to Capital, Special": 435,
  "Agriculture": 436,
  "Land and Resource Management": 437,
  "Government Efficiency and Reform": 438,
  "Cybersecurity, Select": 439,
  "Higher Education Governance, Excellence, and Transparency, Oversight": 440,
  "Veteran Affairs and Military Installations Subcommittee on Border Security": 441,
  "Personal Privacy Task Force": 442,
  "Water Resources": 443,
  "Aging": 444,
  "Law Enforcement": 445,
  "Electronic Government, Legislative Oversight": 446,
  "Special Purpose Districts, Select": 447,
  "Public School Finance, Select Subcommittee on Facilities": 448,
  "Criminal Justice": 449,
  "Mentally Retarded Persons Act of 1977, Task Force on": 450,
  "Health Services, Interim": 451,
  "State, Federal, and International Relations": 452,
  "Criminal Justice, Interim": 453,
  "21st Century Colleges and Universities, Special": 454,
  "Public School Finance, Select Subcommittee on High School": 455,
  "Binational Health Benefit Plan Coverage, Interim": 456,
  "State Guaranty Funds, Select": 457,
  "House Administration": 458,
  "Election Contest District 48, Select ": 459,
  "Teacher Health Insurance, Select": 460,
  "Emerging Issues in Texas Law Enforcement, Select": 461,
  "Judiciary and Civil Jurisprudence": 462,
  "Funding Issues in Education, Interim": 463,
  "Advertising Public Notices": 464,
  "Charitable Bingo, Interim": 465,
  "Insurance Subcommittee on Budget and Oversight": 466,
  "Natural Resource Public Interest Counsel, Interim": 467,
  "International Relations and Economic Development": 468,
  "Civil Justice, Interim": 469,
  "Public School Finance System": 470,
  "Water, Agriculture, and Rural Affairs": 471,
  "Public School Finance, Select, Executive Committee": 472,
  "Ways and Means": 473,
  "Edwards Aquifer, Oversight": 474,
  "Government Reform, Select": 475,
  "State Water Funding": 476,
  "Corrections Subcommittee on Budget and Oversight": 477,
  "Water Resources Development and Management, Interim": 478,
  "State Cultural and Recreational Resources": 479,
  "Operation and Management of the Texas Youth Commission, Select": 480,
  "Local Government Ways and Means": 481,
  "Children's Health Insurance, Interim": 482,
  "Hurricane Ike Storm Devastation to the Texas Gulf Coast, Select": 483,
  "Public Safety": 484,
  "To Protect All Texans, Special": 485,
  "Judicial Affairs": 486,
  "Judicial Selection, Texas Commission on": 487,
  "Natural Resources": 488,
  "Manufacturing, Interim": 489,
  "Intergovernmental Relations Subcommittee on Urban Affairs": 490,
  "Water and Rural Affairs": 491,
  "Effects of Sludge Disposal, Interim": 492,
  "Appropriations": 493,
  "Economic Development, Interim": 494,
  "State Affairs Subcommittee on Budget and Oversight": 495,
  "Appropriations Subcommittee on Special Issues (Including Article IX)": 496,
  "Windham School District, Select": 497,
  "Labor and Employment Relations Subcommittee on Budget and Oversight": 498,
  "Workers' Compensation, Select, Interim": 499,
  "Appropriations Subcommittee on General Government (Articles I, VI, and VII)": 500,
  "Nutrition and Health in Public Schools": 501,
  "Federal Environmental Regulation, Select": 502,
  "Windstorm Coverage and Budgetary Impact, Interim": 503,
  "Texas Response to Federal Sequestration, Interim": 504,
  "Rate and Policy Form Regulation, Select": 505,
  "Business and Commerce Subcommittee on Emerging Technologies and Economic Development": 506,
  "Water Policy, Select": 507,
  "State Loans and Grants, House Joint": 508,
  "Agriculture, Rural Affairs, and Homeland Security": 509,
  "Long Term Care, Legislative Oversight": 510,
  "Corrections Subcommittee on Oversight": 511,
  "State and Local Drug Control, Task Force on": 512,
  "Funding Options for the New Texas Cultural Endowment Fund, Interim": 513,
  "Title Insurance, Interim": 514,
  "State Affairs, Interim": 515
}

second_committee_to_number = {
  "Border & International Affairs": 54,
  "Select Committee": 62,
  "Children's Health Insurance (Interim)": 482,
  "Power of Eminent Domain (Interim)": 288,
  "Subcommittee on Elections and Ethics": 408,
  "Local Government": 2,
  "Child Protective Services, Special": 5,
  "Prompt Payment of Health Care Providers": 272,
  "B & O-Transportation": 400,
  "Homeland Security & Public Safety": 242,
  "Higher Education Formula Funding, Interim": 222,
  "Funding Issues in Education (Interim)": 463,
  "Charitable Bingo (Interim)": 465,
  "Oversight of Compact Facility": 201,
  "Texas Agricultural Extension Service (Int.)": 371,
  "B & O-Public Health": 259,
  "B & O-Liquor Regulations": 69,
  "Appropriations-S/C on General Government": 76,
  "Jurisprudence": 15,
  "Emerging Issues In Texas Law Enforcement, Select": 461,
  "Fiscal Impact of Texas Border Support Operations, Select": 17,
  "Health Insurance Risk Pool Deficit (Interim)": 25,
  "Public Education-S/C on Educator Quality": 382,
  "Open Government, Select": 23,
  "Water": 443,
  "Seacoast Territory Insurance": 27,
  "Public Education": 28,
  "Construction-Related Workers' Comp, Select": 64,
  "Recruitment of Firearms & Ammunition Manufacturers": 29,
  "NAFTA (Interim)": 142,
  "Public School-S/C on Facilities": 158,
  "Resolutions Calendars": 31,
  "Binational Alcohol and Substance Abuse": 155,
  "The Robb Elementary Shooting, Investigative": 36,
  "County Affairs": 37,
  "Finance-S/C on Public Education Funding": 412,
  "Natural Resource Public Interest Counsel": 467,
  "Higher & Public Education Finance, Select": 353,
  "Subcommittee on Water": 338,
  "Oversight of Criminal Justice": 449,
  "Government Efficiency & Reform": 438,
  "Water Desalination": 44,
  "Nominations": 45,
  "Calendars": 46,
  "Investments & Financial Services": 40,
  "Fiscal Stability, Select": 48,
  "Subcommittee on Base Realignment and Closure": 47,
  "Appropriations-S/C on Health & Human Services": 49,
  "Environmental Regulation": 50,
  "Employment Practices, Select": 51,
  "Appropriations-S/C on Duplication of Services": 18,
  "B & O-Public Safety": 484,
  "Border and International Affairs": 54,
  "Defense & Veterans' Affairs": 429,
  "Child Protection, Select": 56,
  "Administration": 57,
  "Pensions and Investments": 58,
  "Gangs & Juvenile Justice (Interim)": 122,
  "Public School-S/C on Tax": 470,
  "Community-Based Care Transition, Oversight": 60,
  "School Finance Weights, Allotments & Adjustments, Select": 345,
  "Transportation (Interim)": 20,
  "Statewide Health Care Costs, Select": 65,
  "Higher Education Excellence Funding": 296,
  "International & Cultural Relations": 6,
  "State Affairs (Interim)": 515,
  "Tax Reform & Public School Finance, Select": 248,
  "General Investigating Committee-Special": 55,
  "Health & Human Services": 168,
  "Appropriations-S/C on Govt. Efficiency & Oper": 249,
  "Appropriations - S/C on Article II": 363,
  "State Investment Policy (Interim)": 238,
  "Liquor Regulation": 69,
  "General Investigating Committee": 148,
  "Criminal Justice Reform, Interim Study": 74,
  "S/C on Flooding & Evacuations": 138,
  "Revenue & Public Education Funding, Select": 151,
  "Juvenile Justice and Family Issues": 82,
  "Culture, Recreation, & Tourism": 411,
  "Violence in Schools & School Security, Select": 85,
  "Economic Competitiveness, Select": 86,
  "Senate Chamber Review": 87,
  "Water Policy, Select Interim": 507,
  "Veteran Affairs & Border Security": 140,
  "Property Tax Relief, Select": 90,
  "Study Comsn on Water Environmental Flows": 311,
  "Use of Prior Authorization & Utilization Review Processes": 350,
  "Government Facilities, Select": 95,
  "Juvenile Justice & Child Support (Interim)": 267,
  "Transportation Funding, Expenditures & Finance, Select": 80,
  "Ethics, Select": 100,
  "Youth Health & Safety, Select": 157,
  "Economic Development, Select": 102,
  "S/C on Capital Funding for Higher Education": 134,
  "Health Care Education & Training, Select": 360,
  "Housing (Interim Committee)": 153,
  "Texas Infrastructure Resiliency Fund Advisory": 109,
  "B & O-Corrections": 340,
  "Business & Industry": 319,
  "Rules and Resolutions": 110,
  "Appropriations-S/C on Article IX": 363,
  "Government Reform": 114,
  "Education Policy for a Skilled Workforce": 115,
  "Oversight of Bexar Metropolitan Water District": 161,
  "B & O-Financial Institutions": 169,
  "Cmte of the Whole on Leg & Cong Redistricting": 189,
  "State Health Care Expenditures, Select": 118,
  "S/C on Emerging Technologies & Economic Dev.": 506,
  "Oversight of Medicaid Reform": 438,
  "Education Reform & Public School Finance, Sel": 175,
  "Cmte of the Whole on Red., Ethics & Elections": 189,
  "Veterans Health, Select": 123,
  "Appropriations-S/C on Dedicated Funds": 261,
  "Permits Processing at TCEQ": 0,
  "Economic Development Incentives, Select": 127,
  "B & O-Insurance": 401,
  "Constitutional Revision, Select": 129,
  "Election Security, Select": 130,
  "Veteran Affairs & Military Installations-Spec": 217,
  "Property Tax Reform, Select": 132,
  "Subcommittee I": 62,
  "Appropriations - S/C on Articles VI, VII & VIII": 363,
  "State Judicial Salaries": 136,
  "Cultural and Hist. Resources": 42,
  "Appropriations-S/C on Tobacco": 302,
  "Appropriations - S/C on Budget Transparency and Reform": 410,
  "International Relations & Trade": 343,
  "B & O-Ways & Means": 473,
  "B & O-Judiciary": 347,
  "B & O-Cultural & Historical Res.": 42,
  "Investments & Financial Services-S/C on Bond Indebtedness": 143,
  "Federal Economic Stabilization Funding, Select": 141,
  "Use of the Sales Tax on Sporting Goods": 389,
  "Sex Offenders (Interim)": 214,
  "Partnership Advisory Commission": 144,
  "Pensions & Investments": 58,
  "Appropriations - S/C on Articles I, IV, & V": 363,
  "General Investigating": 148,
  "Oversight of Property & Casualty Insurance": 113,
  "Operation & Management of the Texas Youth Commission": 480,
  "Constitutional Issues, Special": 152,
  "Constitutional Rights & Remedies, Select": 316,
  "Economic & Small Business Development - S/C Manufacturing": 317,
  "Higher Education (Interim)": 105,
  "Licensing & Administrative Procedures": 383,
  "Water, Agriculture & Rural Affairs": 471,
  "Regional Issues (Interim)": 260,
  "Subcommittee on Infrastructure": 111,
  "Appropriations-S/C on Education": 22,
  "Transportation Planning, Select": 165,
  "Subcommittee on Agriculture": 66,
  "Environmental Affairs": 166,
  "B & O-Public Education": 28,
  "Appropriations - S/C on Current Fiscal Condition": 131,
  "Financial Institutions": 169,
  "Legislative Oversight of Long-Term Care": 235,
  "Subcommittee on Border Affairs": 39,
  "Appropriations-S/C on Stimulus": 245,
  "Managed Care and Consumer Protections (Int.)": 327,
  "Economic & Small Business Development": 341,
  "Alzheimer's Disease": 171,
  "Subcommittee Lease of State Water Rights, Int": 280,
  "S/C on Ag., Rural Affairs & Coastal Resources": 398,
  "Civil Justice (Interim)": 469,
  "Oversight of Electronic Government Projects": 446,
  "Select Committee on Public Education": 412,
  "Committee of the Whole": 315,
  "B & O-Natural Resources": 488,
  "Human Services": 176,
  "Natural Resources & Economic Development": 179,
  "Finance-S/C on Fiscal Matters": 417,
  "Affordable Housing (Interim)": 377,
  "Human Trafficking": 178,
  "Electric Utility Restructuring - Special": 181,
  "Texas Ports, Select": 180,
  "Border Security": 184,
  "Judicial Selection": 186,
  "Title Insurance (Interim)": 514,
  "State, Federal & International Relations": 67,
  "B & O-Agriculture & Livestock": 395,
  "International Relations & Economic Development": 468,
  "Technology, Economic Development & Workforce": 12,
  "Health Services": 193,
  "Economic & Small Business Development-S/C on Small Business": 244,
  "State Bond Revenues, Select": 195,
  "Transparency in State Agency Operations, Select": 196,
  "Regulatory Agencies": 307,
  "Government Facilities": 201,
  "State Employee Compensation and Benefits": 73,
  "Public Education Reform, Select": 207,
  "Land & Resource Management": 437,
  "Intergovernmental Relations": 208,
  "International Relations, Trade & Technology": 139,
  "Initiative & Referendum (Interim)": 362,
  "Elections": 209,
  "Public School-S/C on Completion & Dropout": 283,
  "Subcommittee on Veteran Affairs": 39,
  "State Water Implementation Fund for Texas Advisory": 218,
  "Oversight of HHS Eligibility System": 112,
  "Public School Finance, Select": 220,
  "Culture, Recreation & Tourism": 411,
  "Windstorm Coverage & Budget Impact (Interim)": 503,
  "Oversight of Higher Ed Governance, Excellence & Transparency": 440,
  "Civil Practices": 223,
  "Approps. - S/C on Strategic Fiscal Rev. & Fed. Relief Funds": 266,
  "Economic Stabilization Fund Balance, Select": 227,
  "Public School-S/C on High School": 455,
  "Investment in Information Technology Improvement, Oversight": 325,
  "Transportation Funding, Select": 228,
  "Border & Intergovernmental Affairs": 117,
  "Infrastructure Development and Security": 233,
  "S/C on Base Realignment and Closure": 47,
  "Oversight of Windstorm Insurance": 284,
  "Texas Lottery": 146,
  "Economic Development (Interim)": 494,
  "Emissions and Clean Air, Special Committee on": 210,
  "Health & Human Services (Interim)": 364,
  "Agriculture, Rural Affairs & Homeland Security": 509,
  "Redistricting, Special": 241,
  "Pensions": 246,
  "Oversight of Telecomm Competitiveness": 86,
  "Rules & Resolutions": 110,
  "Appropriations - S/C on Articles VI, VII, & VIII": 500,
  "State Loans and Grants (Interim)": 508,
  "Labor and Employment Relations": 250,
  "Finance-S/C on Higher Education Funding": 264,
  "Urban Affairs": 255,
  "S/C on Higher Education": 297,
  "Appropriations - S/C on Article III": 363,
  "Transportation-S/C on Long-term Infrastructure Planning": 349,
  "B & O-Business & Commerce": 10,
  "Finance-S/C on Articles VI & VII": 375,
  "Public Health": 259,
  "Appropriations-S/C on Special Issues": 496,
  "Federal Legislation, Select": 262,
  "Public Information (Interim)": 322,
  "Property Tax": 265,
  "Blue Ribbon Task Force on Uninsured": 394,
  "B & O-Energy": 269,
  "Workers' Compensation, Select Interim": 499,
  "Economic Development-S/C on Public-Private Partnerships": 163,
  "Energy": 269,
  "Juvenile Justice & Family Issues": 82,
  "Open Government": 274,
  "Water & Rural Affairs": 491,
  "Public School-S/C on Governance": 470,
  "Government Efficiency & Accountability, Select": 374,
  "Election Contests, Select": 281,
  "State Sovereignty, Select": 282,
  "Technology": 285,
  "Ethics Laws, Select": 287,
  "Subcommittee III": 185,
  "Environmental Flows": 311,
  "Home Health & Assisted Living Facilities(Int)": 183,
  "B & O-Human Services": 168,
  "Veteran Affairs & Military Installations-S/C Border Security": 441,
  "Natural Resources (Interim)": 355,
  "Criminal Commitments of Indiv. w/ Mental Retardation, Select": 203,
  "Higher Education": 297,
  "Government Transparency & Operation": 135,
  "Military & Veterans Affairs, Select Comt. on": 234,
  "Special Purpose Districts": 299,
  "Electric Generation Capacity, Select": 172,
  "B & O-Labor & Employment Rel.": 250,
  "Legislative Oversight on Higher Education": 21,
  "Cmte. of the Whole Senate on Redistricting": 189,
  "Government Organization": 303,
  "Veteran Affairs": 304,
  "Agriculture Policy": 306,
  "Regulated Industries": 307,
  "Ports, Select": 310,
  "Redistricting": 314,
  "Committee of the Whole Senate": 315,
  "S/C on Agriculture & Coastal Resources": 43,
  "Transportation & Homeland Security": 145,
  "Medical Peer Review Process (Interim)": 0,
  "Natural Resources-S/C on Special Water Districts": 424,
  "Rural Development, Select": 326,
  "Health Benefit Mandates (Interim)": 329,
  "Property Tax Reform & Relief, Select": 188,
  "Cruise Industry Development": 336,
  "Health Care Reform, Select": 337,
  "Legislative Oversight on Long-Term Care": 235,
  "Future of College Sports in Texas, Select": 342,
  "Corrections": 340,
  "Mass Violence Prevention & Community Safety, Select": 106,
  "International Relations and Trade": 343,
  "Elections & Ethics": 209,
  "Redistricting, Select": 344,
  "Oversight of Medicaid Reform Waiver": 335,
  "Agriculture & Wildlife Management": 324,
  "Judiciary": 347,
  "Impact of Electric Util. Restructuring on Tax": 181,
  "Economic Development": 348,
  "State Real Property Data Collect, Report & Assess, Select": 160,
  "Federalism & Fiscal Responsibility, Select": 359,
  "Oversight of Electric Utility Restructuring": 181,
  "Defense Affairs and State-Federal Relations": 352,
  "Property Tax Relief and Appraisal Reform, Select": 354,
  "Private Activity Bonds, Interim": 356,
  "Veteran Affairs & Military Installations": 217,
  "Criminal Procedure Reform, Select": 358,
  "General Investigating & Ethics": 137,
  "International Trade & Intergovernmental Affairs": 278,
  "Sex Offenders Statutes, Select": 391,
  "State Affairs": 361,
  "State & Federal Power & Responsibility, Select": 293,
  "Public School-S/C on Benefits & Compensation": 252,
  "Health and Human Services, Select": 366,
  "Aggregate Production Operations, Interim Study": 369,
  "Appropriations-S/C on Business & Economic Development": 413,
  "Subcommittee II": 415,
  "Appropriations-S/C on Hurricane": 229,
  "Pensions, Investments & Financial Services": 119,
  "Texas Privacy Protection Advisory Council": 294,
  "Mental Health, Select": 376,
  "Health & Long-Term Care Insurance Incentives": 430,
  "People with Mental Disabilities (Interim)": 216,
  "Private Participation in Toll Projects": 38,
  "B & O-Environmental Affairs": 166,
  "Retirement and Aging": 380,
  "Ways & Means": 473,
  "Annexation (Interim)": 279,
  "Finance-S/C on Medicaid": 26,
  "Juvenile DWI Laws (Interim)": 239,
  "Judicial Interpretations of Law, Select": 386,
  "Appropriations - S/C on Articles I, IV & V": 363,
  "Agriculture & Livestock": 395,
  "Border Wait Times": 387,
  "TNRCC Funding (Interim)": 351,
  "State Recreational Resources": 390,
  "Appropriations-S/C on Emoluments": 149,
  "Prescribing & Dispensing Controlled Substances, Interim": 268,
  "Education": 393,
  "Public School-S/C on Alternative Methods": 124,
  "Texas Ports, Innovation & Infrastructure, Select": 273,
  "Coastal Barrier System": 403,
  "Insurance": 401,
  "Transportation": 400,
  "Public School Accountability, Select": 404,
  "Intermediate Care Facility Services, Select": 312,
  "General Matters": 148,
  "Judiciary & Civil Jurisprudence": 462,
  "Hopwood, State Contract & Employmt. Practices": 330,
  "Opioids & Substance Abuse, Select": 155,
  "Energy Resources": 414,
  "Emergency Preparedness, Select": 416,
  "Nutrition & Health in Public Schools": 501,
  "General Revenue Dedicated Accounts, Interim": 419,
  "Agriculture & Rural Affairs": 420,
  "Voter Identification & Voter Fraud, Select": 275,
  "TRS Health Benefit Plans": 425,
  "Criminal Jurisprudence": 427,
  "Finance": 431,
  "Health and Human Services Block Grants (Int.)": 170,
  "Dyslexia & Related Disorders, Interim": 191,
  "Appropriations-S/C on Criminal Justice": 173,
  "Legislative Districts": 192,
  "Criminal Justice (Interim)": 453,
  "Agriculture": 436,
  "Oversight of Edwards Aquifer": 230,
  "Public School-S/C on Incentives & Account.": 308,
  "Hurricane Ike Devastation, Select": 483,
  "Disclosure of Emergency Call Information, Interim": 365,
  "Land and Resource Management": 437,
  "B & O-Elections": 209,
  "Cybersecurity, Select": 439,
  "Water Resources": 443,
  "Aging": 444,
  "Law Enforcement": 445,
  "Congressional Districts": 299,
  "Driver's License Issuance & Renewal, Select": 225,
  "Public School-S/C on Cost Adjustments": 88,
  "Special Purpose Districts, Select": 447,
  "Criminal Justice": 449,
  "Higher Education-S/C on Post-Secondary & Workforce Readiness": 243,
  "B & O-Judicial Affairs": 486,
  "Health Services, Interim": 451,
  "House Administration": 458,
  "Border Affairs - Special": 1,
  "Teacher Health Insurance, Select": 460,
  "Investments & Banking": 156,
  "Advertising Public Notices": 464,
  "Child Welfare & Foster Care, Select": 154,
  "Education (Interim)": 150,
  "B & O-Higher Education": 297,
  "Local Government Ways & Means": 481,
  "Health & Human Services Transition, Oversight": 406,
  "Public School Finance System": 470,
  "Breeding White-Tailed and Mule Deer, Select": 14,
  "Subcommittee on Higher Education": 21,
  "Government Reform, Select": 475,
  "State Water Funding": 476,
  "B & O-State Affairs": 361,
  "Business & Commerce": 10,
  "Appropriations-S/C on Regulatory": 328,
  "State Cultural and Recreational Resources": 479,
  "Local Government Ways and Means": 481,
  "Study Commission on Transportation Financing": 8,
  "Public Safety": 484,
  "To Protect All Texans, Special": 485,
  "Judicial Affairs": 486,
  "Subcommittee on Technology & Business Growth": 206,
  "Manufacturing, Interim": 489,
  "Natural Resources": 488,
  "Science & Technology": 120,
  "Electric Utility Restructuring (Interim)": 116,
  "Appropriations": 493,
  "Finance-S/C on Public Safety": 33,
  "Windham School District, Select": 497,
  "Appropriations - S/C on Infrastructure, Resiliency & Invest": 35,
  "Defense Affairs & State-Federal Relations": 352,
  "Federal Environmental Regulation, Select": 502,
  "Local & Consent Calendars": 221,
  "Agriculture, Water & Rural Affairs": 93,
  "Appropriations - S/C on Budget Transparency & Reform": 410,
  "Election Contest, Select": 281,
  "Response to Federal Sequestration, Interim": 504
}