import pandas as pd
import numpy as np
import requests
import re
import json
from os import path
from bs4 import BeautifulSoup
from committee_dict import first_committee_to_number as committee_to_number

leg_sess = 71

while leg_sess <= 87:
    data = {
        "leg_sess": -1,
        "male_house_members": 0,
        "male_senate_members": 0,
        "female_house_members": 0,
        "female_senate_members": 0,
        "democrat_house_members": 0,
        "democrat_senate_members": 0,
        "republican_house_members": 0,
        "republican_senate_members": 0,
        "house_incumbents": 0,
        "senate_incumbents": 0,
        "house_freshman": 0,
        "senate_freshman": 0,
        "house_members_age_under_30": 0,
        "senate_members_age_under_30": 0,
        "house_members_age_30_to_39": 0,
        "senate_members_age_30_to_39": 0,
        "house_members_age_40_to_49": 0,
        "senate_members_age_40_to_49": 0,
        "house_members_age_50_to_59": 0,
        "senate_members_age_50_to_59": 0,
        "house_members_age_60_to_69": 0,
        "senate_members_age_60_to_69": 0,
        "house_members_age_over_70": 0,
        "senate_members_age_over_70": 0,
        "committee_0_republicans": 0,
        "committee_0_democrats": 0,
        "committee_1_republicans": 0,
        "committee_1_democrats": 0,
        "committee_2_republicans": 0,
        "committee_2_democrats": 0,
        "committee_3_republicans": 0,
        "committee_3_democrats": 0,
        "committee_4_republicans": 0,
        "committee_4_democrats": 0,
        "committee_5_republicans": 0,
        "committee_5_democrats": 0,
        "committee_6_republicans": 0,
        "committee_6_democrats": 0,
        "committee_7_republicans": 0,
        "committee_7_democrats": 0,
        "committee_8_republicans": 0,
        "committee_8_democrats": 0,
        "committee_9_republicans": 0,
        "committee_9_democrats": 0,
        "committee_10_republicans": 0,
        "committee_10_democrats": 0,
        "committee_11_republicans": 0,
        "committee_11_democrats": 0,
        "committee_12_republicans": 0,
        "committee_12_democrats": 0,
        "committee_13_republicans": 0,
        "committee_13_democrats": 0,
        "committee_14_republicans": 0,
        "committee_14_democrats": 0,
        "committee_15_republicans": 0,
        "committee_15_democrats": 0,
        "committee_16_republicans": 0,
        "committee_16_democrats": 0,
        "committee_17_republicans": 0,
        "committee_17_democrats": 0,
        "committee_18_republicans": 0,
        "committee_18_democrats": 0,
        "committee_19_republicans": 0,
        "committee_19_democrats": 0,
        "committee_20_republicans": 0,
        "committee_20_democrats": 0,
        "committee_21_republicans": 0,
        "committee_21_democrats": 0,
        "committee_22_republicans": 0,
        "committee_22_democrats": 0,
        "committee_23_republicans": 0,
        "committee_23_democrats": 0,
        "committee_24_republicans": 0,
        "committee_24_democrats": 0,
        "committee_25_republicans": 0,
        "committee_25_democrats": 0,
        "committee_26_republicans": 0,
        "committee_26_democrats": 0,
        "committee_27_republicans": 0,
        "committee_27_democrats": 0,
        "committee_28_republicans": 0,
        "committee_28_democrats": 0,
        "committee_29_republicans": 0,
        "committee_29_democrats": 0,
        "committee_30_republicans": 0,
        "committee_30_democrats": 0,
        "committee_31_republicans": 0,
        "committee_31_democrats": 0,
        "committee_32_republicans": 0,
        "committee_32_democrats": 0,
        "committee_33_republicans": 0,
        "committee_33_democrats": 0,
        "committee_34_republicans": 0,
        "committee_34_democrats": 0,
        "committee_35_republicans": 0,
        "committee_35_democrats": 0,
        "committee_36_republicans": 0,
        "committee_36_democrats": 0,
        "committee_37_republicans": 0,
        "committee_37_democrats": 0,
        "committee_38_republicans": 0,
        "committee_38_democrats": 0,
        "committee_39_republicans": 0,
        "committee_39_democrats": 0,
        "committee_40_republicans": 0,
        "committee_40_democrats": 0,
        "committee_41_republicans": 0,
        "committee_41_democrats": 0,
        "committee_42_republicans": 0,
        "committee_42_democrats": 0,
        "committee_43_republicans": 0,
        "committee_43_democrats": 0,
        "committee_44_republicans": 0,
        "committee_44_democrats": 0,
        "committee_45_republicans": 0,
        "committee_45_democrats": 0,
        "committee_46_republicans": 0,
        "committee_46_democrats": 0,
        "committee_47_republicans": 0,
        "committee_47_democrats": 0,
        "committee_48_republicans": 0,
        "committee_48_democrats": 0,
        "committee_49_republicans": 0,
        "committee_49_democrats": 0,
        "committee_50_republicans": 0,
        "committee_50_democrats": 0,
        "committee_51_republicans": 0,
        "committee_51_democrats": 0,
        "committee_52_republicans": 0,
        "committee_52_democrats": 0,
        "committee_53_republicans": 0,
        "committee_53_democrats": 0,
        "committee_54_republicans": 0,
        "committee_54_democrats": 0,
        "committee_55_republicans": 0,
        "committee_55_democrats": 0,
        "committee_56_republicans": 0,
        "committee_56_democrats": 0,
        "committee_57_republicans": 0,
        "committee_57_democrats": 0,
        "committee_58_republicans": 0,
        "committee_58_democrats": 0,
        "committee_59_republicans": 0,
        "committee_59_democrats": 0,
        "committee_60_republicans": 0,
        "committee_60_democrats": 0,
        "committee_61_republicans": 0,
        "committee_61_democrats": 0,
        "committee_62_republicans": 0,
        "committee_62_democrats": 0,
        "committee_63_republicans": 0,
        "committee_63_democrats": 0,
        "committee_64_republicans": 0,
        "committee_64_democrats": 0,
        "committee_65_republicans": 0,
        "committee_65_democrats": 0,
        "committee_66_republicans": 0,
        "committee_66_democrats": 0,
        "committee_67_republicans": 0,
        "committee_67_democrats": 0,
        "committee_68_republicans": 0,
        "committee_68_democrats": 0,
        "committee_69_republicans": 0,
        "committee_69_democrats": 0,
        "committee_70_republicans": 0,
        "committee_70_democrats": 0,
        "committee_71_republicans": 0,
        "committee_71_democrats": 0,
        "committee_72_republicans": 0,
        "committee_72_democrats": 0,
        "committee_73_republicans": 0,
        "committee_73_democrats": 0,
        "committee_74_republicans": 0,
        "committee_74_democrats": 0,
        "committee_75_republicans": 0,
        "committee_75_democrats": 0,
        "committee_76_republicans": 0,
        "committee_76_democrats": 0,
        "committee_77_republicans": 0,
        "committee_77_democrats": 0,
        "committee_78_republicans": 0,
        "committee_78_democrats": 0,
        "committee_79_republicans": 0,
        "committee_79_democrats": 0,
        "committee_80_republicans": 0,
        "committee_80_democrats": 0,
        "committee_81_republicans": 0,
        "committee_81_democrats": 0,
        "committee_82_republicans": 0,
        "committee_82_democrats": 0,
        "committee_83_republicans": 0,
        "committee_83_democrats": 0,
        "committee_84_republicans": 0,
        "committee_84_democrats": 0,
        "committee_85_republicans": 0,
        "committee_85_democrats": 0,
        "committee_86_republicans": 0,
        "committee_86_democrats": 0,
        "committee_87_republicans": 0,
        "committee_87_democrats": 0,
        "committee_88_republicans": 0,
        "committee_88_democrats": 0,
        "committee_89_republicans": 0,
        "committee_89_democrats": 0,
        "committee_90_republicans": 0,
        "committee_90_democrats": 0,
        "committee_91_republicans": 0,
        "committee_91_democrats": 0,
        "committee_92_republicans": 0,
        "committee_92_democrats": 0,
        "committee_93_republicans": 0,
        "committee_93_democrats": 0,
        "committee_94_republicans": 0,
        "committee_94_democrats": 0,
        "committee_95_republicans": 0,
        "committee_95_democrats": 0,
        "committee_96_republicans": 0,
        "committee_96_democrats": 0,
        "committee_97_republicans": 0,
        "committee_97_democrats": 0,
        "committee_98_republicans": 0,
        "committee_98_democrats": 0,
        "committee_99_republicans": 0,
        "committee_99_democrats": 0,
        "committee_100_republicans": 0,
        "committee_100_democrats": 0,
        "committee_101_republicans": 0,
        "committee_101_democrats": 0,
        "committee_102_republicans": 0,
        "committee_102_democrats": 0,
        "committee_103_republicans": 0,
        "committee_103_democrats": 0,
        "committee_104_republicans": 0,
        "committee_104_democrats": 0,
        "committee_105_republicans": 0,
        "committee_105_democrats": 0,
        "committee_106_republicans": 0,
        "committee_106_democrats": 0,
        "committee_107_republicans": 0,
        "committee_107_democrats": 0,
        "committee_108_republicans": 0,
        "committee_108_democrats": 0,
        "committee_109_republicans": 0,
        "committee_109_democrats": 0,
        "committee_110_republicans": 0,
        "committee_110_democrats": 0,
        "committee_111_republicans": 0,
        "committee_111_democrats": 0,
        "committee_112_republicans": 0,
        "committee_112_democrats": 0,
        "committee_113_republicans": 0,
        "committee_113_democrats": 0,
        "committee_114_republicans": 0,
        "committee_114_democrats": 0,
        "committee_115_republicans": 0,
        "committee_115_democrats": 0,
        "committee_116_republicans": 0,
        "committee_116_democrats": 0,
        "committee_117_republicans": 0,
        "committee_117_democrats": 0,
        "committee_118_republicans": 0,
        "committee_118_democrats": 0,
        "committee_119_republicans": 0,
        "committee_119_democrats": 0,
        "committee_120_republicans": 0,
        "committee_120_democrats": 0,
        "committee_121_republicans": 0,
        "committee_121_democrats": 0,
        "committee_122_republicans": 0,
        "committee_122_democrats": 0,
        "committee_123_republicans": 0,
        "committee_123_democrats": 0,
        "committee_124_republicans": 0,
        "committee_124_democrats": 0,
        "committee_125_republicans": 0,
        "committee_125_democrats": 0,
        "committee_126_republicans": 0,
        "committee_126_democrats": 0,
        "committee_127_republicans": 0,
        "committee_127_democrats": 0,
        "committee_128_republicans": 0,
        "committee_128_democrats": 0,
        "committee_129_republicans": 0,
        "committee_129_democrats": 0,
        "committee_130_republicans": 0,
        "committee_130_democrats": 0,
        "committee_131_republicans": 0,
        "committee_131_democrats": 0,
        "committee_132_republicans": 0,
        "committee_132_democrats": 0,
        "committee_133_republicans": 0,
        "committee_133_democrats": 0,
        "committee_134_republicans": 0,
        "committee_134_democrats": 0,
        "committee_135_republicans": 0,
        "committee_135_democrats": 0,
        "committee_136_republicans": 0,
        "committee_136_democrats": 0,
        "committee_137_republicans": 0,
        "committee_137_democrats": 0,
        "committee_138_republicans": 0,
        "committee_138_democrats": 0,
        "committee_139_republicans": 0,
        "committee_139_democrats": 0,
        "committee_140_republicans": 0,
        "committee_140_democrats": 0,
        "committee_141_republicans": 0,
        "committee_141_democrats": 0,
        "committee_142_republicans": 0,
        "committee_142_democrats": 0,
        "committee_143_republicans": 0,
        "committee_143_democrats": 0,
        "committee_144_republicans": 0,
        "committee_144_democrats": 0,
        "committee_145_republicans": 0,
        "committee_145_democrats": 0,
        "committee_146_republicans": 0,
        "committee_146_democrats": 0,
        "committee_147_republicans": 0,
        "committee_147_democrats": 0,
        "committee_148_republicans": 0,
        "committee_148_democrats": 0,
        "committee_149_republicans": 0,
        "committee_149_democrats": 0,
        "committee_150_republicans": 0,
        "committee_150_democrats": 0,
        "committee_151_republicans": 0,
        "committee_151_democrats": 0,
        "committee_152_republicans": 0,
        "committee_152_democrats": 0,
        "committee_153_republicans": 0,
        "committee_153_democrats": 0,
        "committee_154_republicans": 0,
        "committee_154_democrats": 0,
        "committee_155_republicans": 0,
        "committee_155_democrats": 0,
        "committee_156_republicans": 0,
        "committee_156_democrats": 0,
        "committee_157_republicans": 0,
        "committee_157_democrats": 0,
        "committee_158_republicans": 0,
        "committee_158_democrats": 0,
        "committee_159_republicans": 0,
        "committee_159_democrats": 0,
        "committee_160_republicans": 0,
        "committee_160_democrats": 0,
        "committee_161_republicans": 0,
        "committee_161_democrats": 0,
        "committee_162_republicans": 0,
        "committee_162_democrats": 0,
        "committee_163_republicans": 0,
        "committee_163_democrats": 0,
        "committee_164_republicans": 0,
        "committee_164_democrats": 0,
        "committee_165_republicans": 0,
        "committee_165_democrats": 0,
        "committee_166_republicans": 0,
        "committee_166_democrats": 0,
        "committee_167_republicans": 0,
        "committee_167_democrats": 0,
        "committee_168_republicans": 0,
        "committee_168_democrats": 0,
        "committee_169_republicans": 0,
        "committee_169_democrats": 0,
        "committee_170_republicans": 0,
        "committee_170_democrats": 0,
        "committee_171_republicans": 0,
        "committee_171_democrats": 0,
        "committee_172_republicans": 0,
        "committee_172_democrats": 0,
        "committee_173_republicans": 0,
        "committee_173_democrats": 0,
        "committee_174_republicans": 0,
        "committee_174_democrats": 0,
        "committee_175_republicans": 0,
        "committee_175_democrats": 0,
        "committee_176_republicans": 0,
        "committee_176_democrats": 0,
        "committee_177_republicans": 0,
        "committee_177_democrats": 0,
        "committee_178_republicans": 0,
        "committee_178_democrats": 0,
        "committee_179_republicans": 0,
        "committee_179_democrats": 0,
        "committee_180_republicans": 0,
        "committee_180_democrats": 0,
        "committee_181_republicans": 0,
        "committee_181_democrats": 0,
        "committee_182_republicans": 0,
        "committee_182_democrats": 0,
        "committee_183_republicans": 0,
        "committee_183_democrats": 0,
        "committee_184_republicans": 0,
        "committee_184_democrats": 0,
        "committee_185_republicans": 0,
        "committee_185_democrats": 0,
        "committee_186_republicans": 0,
        "committee_186_democrats": 0,
        "committee_187_republicans": 0,
        "committee_187_democrats": 0,
        "committee_188_republicans": 0,
        "committee_188_democrats": 0,
        "committee_189_republicans": 0,
        "committee_189_democrats": 0,
        "committee_190_republicans": 0,
        "committee_190_democrats": 0,
        "committee_191_republicans": 0,
        "committee_191_democrats": 0,
        "committee_192_republicans": 0,
        "committee_192_democrats": 0,
        "committee_193_republicans": 0,
        "committee_193_democrats": 0,
        "committee_194_republicans": 0,
        "committee_194_democrats": 0,
        "committee_195_republicans": 0,
        "committee_195_democrats": 0,
        "committee_196_republicans": 0,
        "committee_196_democrats": 0,
        "committee_197_republicans": 0,
        "committee_197_democrats": 0,
        "committee_198_republicans": 0,
        "committee_198_democrats": 0,
        "committee_199_republicans": 0,
        "committee_199_democrats": 0,
        "committee_200_republicans": 0,
        "committee_200_democrats": 0,
        "committee_201_republicans": 0,
        "committee_201_democrats": 0,
        "committee_202_republicans": 0,
        "committee_202_democrats": 0,
        "committee_203_republicans": 0,
        "committee_203_democrats": 0,
        "committee_204_republicans": 0,
        "committee_204_democrats": 0,
        "committee_205_republicans": 0,
        "committee_205_democrats": 0,
        "committee_206_republicans": 0,
        "committee_206_democrats": 0,
        "committee_207_republicans": 0,
        "committee_207_democrats": 0,
        "committee_208_republicans": 0,
        "committee_208_democrats": 0,
        "committee_209_republicans": 0,
        "committee_209_democrats": 0,
        "committee_210_republicans": 0,
        "committee_210_democrats": 0,
        "committee_211_republicans": 0,
        "committee_211_democrats": 0,
        "committee_212_republicans": 0,
        "committee_212_democrats": 0,
        "committee_213_republicans": 0,
        "committee_213_democrats": 0,
        "committee_214_republicans": 0,
        "committee_214_democrats": 0,
        "committee_215_republicans": 0,
        "committee_215_democrats": 0,
        "committee_216_republicans": 0,
        "committee_216_democrats": 0,
        "committee_217_republicans": 0,
        "committee_217_democrats": 0,
        "committee_218_republicans": 0,
        "committee_218_democrats": 0,
        "committee_219_republicans": 0,
        "committee_219_democrats": 0,
        "committee_220_republicans": 0,
        "committee_220_democrats": 0,
        "committee_221_republicans": 0,
        "committee_221_democrats": 0,
        "committee_222_republicans": 0,
        "committee_222_democrats": 0,
        "committee_223_republicans": 0,
        "committee_223_democrats": 0,
        "committee_224_republicans": 0,
        "committee_224_democrats": 0,
        "committee_225_republicans": 0,
        "committee_225_democrats": 0,
        "committee_226_republicans": 0,
        "committee_226_democrats": 0,
        "committee_227_republicans": 0,
        "committee_227_democrats": 0,
        "committee_228_republicans": 0,
        "committee_228_democrats": 0,
        "committee_229_republicans": 0,
        "committee_229_democrats": 0,
        "committee_230_republicans": 0,
        "committee_230_democrats": 0,
        "committee_231_republicans": 0,
        "committee_231_democrats": 0,
        "committee_232_republicans": 0,
        "committee_232_democrats": 0,
        "committee_233_republicans": 0,
        "committee_233_democrats": 0,
        "committee_234_republicans": 0,
        "committee_234_democrats": 0,
        "committee_235_republicans": 0,
        "committee_235_democrats": 0,
        "committee_236_republicans": 0,
        "committee_236_democrats": 0,
        "committee_237_republicans": 0,
        "committee_237_democrats": 0,
        "committee_238_republicans": 0,
        "committee_238_democrats": 0,
        "committee_239_republicans": 0,
        "committee_239_democrats": 0,
        "committee_240_republicans": 0,
        "committee_240_democrats": 0,
        "committee_241_republicans": 0,
        "committee_241_democrats": 0,
        "committee_242_republicans": 0,
        "committee_242_democrats": 0,
        "committee_243_republicans": 0,
        "committee_243_democrats": 0,
        "committee_244_republicans": 0,
        "committee_244_democrats": 0,
        "committee_245_republicans": 0,
        "committee_245_democrats": 0,
        "committee_246_republicans": 0,
        "committee_246_democrats": 0,
        "committee_247_republicans": 0,
        "committee_247_democrats": 0,
        "committee_248_republicans": 0,
        "committee_248_democrats": 0,
        "committee_249_republicans": 0,
        "committee_249_democrats": 0,
        "committee_250_republicans": 0,
        "committee_250_democrats": 0,
        "committee_251_republicans": 0,
        "committee_251_democrats": 0,
        "committee_252_republicans": 0,
        "committee_252_democrats": 0,
        "committee_253_republicans": 0,
        "committee_253_democrats": 0,
        "committee_254_republicans": 0,
        "committee_254_democrats": 0,
        "committee_255_republicans": 0,
        "committee_255_democrats": 0,
        "committee_256_republicans": 0,
        "committee_256_democrats": 0,
        "committee_257_republicans": 0,
        "committee_257_democrats": 0,
        "committee_258_republicans": 0,
        "committee_258_democrats": 0,
        "committee_259_republicans": 0,
        "committee_259_democrats": 0,
        "committee_260_republicans": 0,
        "committee_260_democrats": 0,
        "committee_261_republicans": 0,
        "committee_261_democrats": 0,
        "committee_262_republicans": 0,
        "committee_262_democrats": 0,
        "committee_263_republicans": 0,
        "committee_263_democrats": 0,
        "committee_264_republicans": 0,
        "committee_264_democrats": 0,
        "committee_265_republicans": 0,
        "committee_265_democrats": 0,
        "committee_266_republicans": 0,
        "committee_266_democrats": 0,
        "committee_267_republicans": 0,
        "committee_267_democrats": 0,
        "committee_268_republicans": 0,
        "committee_268_democrats": 0,
        "committee_269_republicans": 0,
        "committee_269_democrats": 0,
        "committee_270_republicans": 0,
        "committee_270_democrats": 0,
        "committee_271_republicans": 0,
        "committee_271_democrats": 0,
        "committee_272_republicans": 0,
        "committee_272_democrats": 0,
        "committee_273_republicans": 0,
        "committee_273_democrats": 0,
        "committee_274_republicans": 0,
        "committee_274_democrats": 0,
        "committee_275_republicans": 0,
        "committee_275_democrats": 0,
        "committee_276_republicans": 0,
        "committee_276_democrats": 0,
        "committee_277_republicans": 0,
        "committee_277_democrats": 0,
        "committee_278_republicans": 0,
        "committee_278_democrats": 0,
        "committee_279_republicans": 0,
        "committee_279_democrats": 0,
        "committee_280_republicans": 0,
        "committee_280_democrats": 0,
        "committee_281_republicans": 0,
        "committee_281_democrats": 0,
        "committee_282_republicans": 0,
        "committee_282_democrats": 0,
        "committee_283_republicans": 0,
        "committee_283_democrats": 0,
        "committee_284_republicans": 0,
        "committee_284_democrats": 0,
        "committee_285_republicans": 0,
        "committee_285_democrats": 0,
        "committee_286_republicans": 0,
        "committee_286_democrats": 0,
        "committee_287_republicans": 0,
        "committee_287_democrats": 0,
        "committee_288_republicans": 0,
        "committee_288_democrats": 0,
        "committee_289_republicans": 0,
        "committee_289_democrats": 0,
        "committee_290_republicans": 0,
        "committee_290_democrats": 0,
        "committee_291_republicans": 0,
        "committee_291_democrats": 0,
        "committee_292_republicans": 0,
        "committee_292_democrats": 0,
        "committee_293_republicans": 0,
        "committee_293_democrats": 0,
        "committee_294_republicans": 0,
        "committee_294_democrats": 0,
        "committee_295_republicans": 0,
        "committee_295_democrats": 0,
        "committee_296_republicans": 0,
        "committee_296_democrats": 0,
        "committee_297_republicans": 0,
        "committee_297_democrats": 0,
        "committee_298_republicans": 0,
        "committee_298_democrats": 0,
        "committee_299_republicans": 0,
        "committee_299_democrats": 0,
        "committee_300_republicans": 0,
        "committee_300_democrats": 0,
        "committee_301_republicans": 0,
        "committee_301_democrats": 0,
        "committee_302_republicans": 0,
        "committee_302_democrats": 0,
        "committee_303_republicans": 0,
        "committee_303_democrats": 0,
        "committee_304_republicans": 0,
        "committee_304_democrats": 0,
        "committee_305_republicans": 0,
        "committee_305_democrats": 0,
        "committee_306_republicans": 0,
        "committee_306_democrats": 0,
        "committee_307_republicans": 0,
        "committee_307_democrats": 0,
        "committee_308_republicans": 0,
        "committee_308_democrats": 0,
        "committee_309_republicans": 0,
        "committee_309_democrats": 0,
        "committee_310_republicans": 0,
        "committee_310_democrats": 0,
        "committee_311_republicans": 0,
        "committee_311_democrats": 0,
        "committee_312_republicans": 0,
        "committee_312_democrats": 0,
        "committee_313_republicans": 0,
        "committee_313_democrats": 0,
        "committee_314_republicans": 0,
        "committee_314_democrats": 0,
        "committee_315_republicans": 0,
        "committee_315_democrats": 0,
        "committee_316_republicans": 0,
        "committee_316_democrats": 0,
        "committee_317_republicans": 0,
        "committee_317_democrats": 0,
        "committee_318_republicans": 0,
        "committee_318_democrats": 0,
        "committee_319_republicans": 0,
        "committee_319_democrats": 0,
        "committee_320_republicans": 0,
        "committee_320_democrats": 0,
        "committee_321_republicans": 0,
        "committee_321_democrats": 0,
        "committee_322_republicans": 0,
        "committee_322_democrats": 0,
        "committee_323_republicans": 0,
        "committee_323_democrats": 0,
        "committee_324_republicans": 0,
        "committee_324_democrats": 0,
        "committee_325_republicans": 0,
        "committee_325_democrats": 0,
        "committee_326_republicans": 0,
        "committee_326_democrats": 0,
        "committee_327_republicans": 0,
        "committee_327_democrats": 0,
        "committee_328_republicans": 0,
        "committee_328_democrats": 0,
        "committee_329_republicans": 0,
        "committee_329_democrats": 0,
        "committee_330_republicans": 0,
        "committee_330_democrats": 0,
        "committee_331_republicans": 0,
        "committee_331_democrats": 0,
        "committee_332_republicans": 0,
        "committee_332_democrats": 0,
        "committee_333_republicans": 0,
        "committee_333_democrats": 0,
        "committee_334_republicans": 0,
        "committee_334_democrats": 0,
        "committee_335_republicans": 0,
        "committee_335_democrats": 0,
        "committee_336_republicans": 0,
        "committee_336_democrats": 0,
        "committee_337_republicans": 0,
        "committee_337_democrats": 0,
        "committee_338_republicans": 0,
        "committee_338_democrats": 0,
        "committee_339_republicans": 0,
        "committee_339_democrats": 0,
        "committee_340_republicans": 0,
        "committee_340_democrats": 0,
        "committee_341_republicans": 0,
        "committee_341_democrats": 0,
        "committee_342_republicans": 0,
        "committee_342_democrats": 0,
        "committee_343_republicans": 0,
        "committee_343_democrats": 0,
        "committee_344_republicans": 0,
        "committee_344_democrats": 0,
        "committee_345_republicans": 0,
        "committee_345_democrats": 0,
        "committee_346_republicans": 0,
        "committee_346_democrats": 0,
        "committee_347_republicans": 0,
        "committee_347_democrats": 0,
        "committee_348_republicans": 0,
        "committee_348_democrats": 0,
        "committee_349_republicans": 0,
        "committee_349_democrats": 0,
        "committee_350_republicans": 0,
        "committee_350_democrats": 0,
        "committee_351_republicans": 0,
        "committee_351_democrats": 0,
        "committee_352_republicans": 0,
        "committee_352_democrats": 0,
        "committee_353_republicans": 0,
        "committee_353_democrats": 0,
        "committee_354_republicans": 0,
        "committee_354_democrats": 0,
        "committee_355_republicans": 0,
        "committee_355_democrats": 0,
        "committee_356_republicans": 0,
        "committee_356_democrats": 0,
        "committee_357_republicans": 0,
        "committee_357_democrats": 0,
        "committee_358_republicans": 0,
        "committee_358_democrats": 0,
        "committee_359_republicans": 0,
        "committee_359_democrats": 0,
        "committee_360_republicans": 0,
        "committee_360_democrats": 0,
        "committee_361_republicans": 0,
        "committee_361_democrats": 0,
        "committee_362_republicans": 0,
        "committee_362_democrats": 0,
        "committee_363_republicans": 0,
        "committee_363_democrats": 0,
        "committee_364_republicans": 0,
        "committee_364_democrats": 0,
        "committee_365_republicans": 0,
        "committee_365_democrats": 0,
        "committee_366_republicans": 0,
        "committee_366_democrats": 0,
        "committee_367_republicans": 0,
        "committee_367_democrats": 0,
        "committee_368_republicans": 0,
        "committee_368_democrats": 0,
        "committee_369_republicans": 0,
        "committee_369_democrats": 0,
        "committee_370_republicans": 0,
        "committee_370_democrats": 0,
        "committee_371_republicans": 0,
        "committee_371_democrats": 0,
        "committee_372_republicans": 0,
        "committee_372_democrats": 0,
        "committee_373_republicans": 0,
        "committee_373_democrats": 0,
        "committee_374_republicans": 0,
        "committee_374_democrats": 0,
        "committee_375_republicans": 0,
        "committee_375_democrats": 0,
        "committee_376_republicans": 0,
        "committee_376_democrats": 0,
        "committee_377_republicans": 0,
        "committee_377_democrats": 0,
        "committee_378_republicans": 0,
        "committee_378_democrats": 0,
        "committee_379_republicans": 0,
        "committee_379_democrats": 0,
        "committee_380_republicans": 0,
        "committee_380_democrats": 0,
        "committee_381_republicans": 0,
        "committee_381_democrats": 0,
        "committee_382_republicans": 0,
        "committee_382_democrats": 0,
        "committee_383_republicans": 0,
        "committee_383_democrats": 0,
        "committee_384_republicans": 0,
        "committee_384_democrats": 0,
        "committee_385_republicans": 0,
        "committee_385_democrats": 0,
        "committee_386_republicans": 0,
        "committee_386_democrats": 0,
        "committee_387_republicans": 0,
        "committee_387_democrats": 0,
        "committee_388_republicans": 0,
        "committee_388_democrats": 0,
        "committee_389_republicans": 0,
        "committee_389_democrats": 0,
        "committee_390_republicans": 0,
        "committee_390_democrats": 0,
        "committee_391_republicans": 0,
        "committee_391_democrats": 0,
        "committee_392_republicans": 0,
        "committee_392_democrats": 0,
        "committee_393_republicans": 0,
        "committee_393_democrats": 0,
        "committee_394_republicans": 0,
        "committee_394_democrats": 0,
        "committee_395_republicans": 0,
        "committee_395_democrats": 0,
        "committee_396_republicans": 0,
        "committee_396_democrats": 0,
        "committee_397_republicans": 0,
        "committee_397_democrats": 0,
        "committee_398_republicans": 0,
        "committee_398_democrats": 0,
        "committee_399_republicans": 0,
        "committee_399_democrats": 0,
        "committee_400_republicans": 0,
        "committee_400_democrats": 0,
        "committee_401_republicans": 0,
        "committee_401_democrats": 0,
        "committee_402_republicans": 0,
        "committee_402_democrats": 0,
        "committee_403_republicans": 0,
        "committee_403_democrats": 0,
        "committee_404_republicans": 0,
        "committee_404_democrats": 0,
        "committee_405_republicans": 0,
        "committee_405_democrats": 0,
        "committee_406_republicans": 0,
        "committee_406_democrats": 0,
        "committee_407_republicans": 0,
        "committee_407_democrats": 0,
        "committee_408_republicans": 0,
        "committee_408_democrats": 0,
        "committee_409_republicans": 0,
        "committee_409_democrats": 0,
        "committee_410_republicans": 0,
        "committee_410_democrats": 0,
        "committee_411_republicans": 0,
        "committee_411_democrats": 0,
        "committee_412_republicans": 0,
        "committee_412_democrats": 0,
        "committee_413_republicans": 0,
        "committee_413_democrats": 0,
        "committee_414_republicans": 0,
        "committee_414_democrats": 0,
        "committee_415_republicans": 0,
        "committee_415_democrats": 0,
        "committee_416_republicans": 0,
        "committee_416_democrats": 0,
        "committee_417_republicans": 0,
        "committee_417_democrats": 0,
        "committee_418_republicans": 0,
        "committee_418_democrats": 0,
        "committee_419_republicans": 0,
        "committee_419_democrats": 0,
        "committee_420_republicans": 0,
        "committee_420_democrats": 0,
        "committee_421_republicans": 0,
        "committee_421_democrats": 0,
        "committee_422_republicans": 0,
        "committee_422_democrats": 0,
        "committee_423_republicans": 0,
        "committee_423_democrats": 0,
        "committee_424_republicans": 0,
        "committee_424_democrats": 0,
        "committee_425_republicans": 0,
        "committee_425_democrats": 0,
        "committee_426_republicans": 0,
        "committee_426_democrats": 0,
        "committee_427_republicans": 0,
        "committee_427_democrats": 0,
        "committee_428_republicans": 0,
        "committee_428_democrats": 0,
        "committee_429_republicans": 0,
        "committee_429_democrats": 0,
        "committee_430_republicans": 0,
        "committee_430_democrats": 0,
        "committee_431_republicans": 0,
        "committee_431_democrats": 0,
        "committee_432_republicans": 0,
        "committee_432_democrats": 0,
        "committee_433_republicans": 0,
        "committee_433_democrats": 0,
        "committee_434_republicans": 0,
        "committee_434_democrats": 0,
        "committee_435_republicans": 0,
        "committee_435_democrats": 0,
        "committee_436_republicans": 0,
        "committee_436_democrats": 0,
        "committee_437_republicans": 0,
        "committee_437_democrats": 0,
        "committee_438_republicans": 0,
        "committee_438_democrats": 0,
        "committee_439_republicans": 0,
        "committee_439_democrats": 0,
        "committee_440_republicans": 0,
        "committee_440_democrats": 0,
        "committee_441_republicans": 0,
        "committee_441_democrats": 0,
        "committee_442_republicans": 0,
        "committee_442_democrats": 0,
        "committee_443_republicans": 0,
        "committee_443_democrats": 0,
        "committee_444_republicans": 0,
        "committee_444_democrats": 0,
        "committee_445_republicans": 0,
        "committee_445_democrats": 0,
        "committee_446_republicans": 0,
        "committee_446_democrats": 0,
        "committee_447_republicans": 0,
        "committee_447_democrats": 0,
        "committee_448_republicans": 0,
        "committee_448_democrats": 0,
        "committee_449_republicans": 0,
        "committee_449_democrats": 0,
        "committee_450_republicans": 0,
        "committee_450_democrats": 0,
        "committee_451_republicans": 0,
        "committee_451_democrats": 0,
        "committee_452_republicans": 0,
        "committee_452_democrats": 0,
        "committee_453_republicans": 0,
        "committee_453_democrats": 0,
        "committee_454_republicans": 0,
        "committee_454_democrats": 0,
        "committee_455_republicans": 0,
        "committee_455_democrats": 0,
        "committee_456_republicans": 0,
        "committee_456_democrats": 0,
        "committee_457_republicans": 0,
        "committee_457_democrats": 0,
        "committee_458_republicans": 0,
        "committee_458_democrats": 0,
        "committee_459_republicans": 0,
        "committee_459_democrats": 0,
        "committee_460_republicans": 0,
        "committee_460_democrats": 0,
        "committee_461_republicans": 0,
        "committee_461_democrats": 0,
        "committee_462_republicans": 0,
        "committee_462_democrats": 0,
        "committee_463_republicans": 0,
        "committee_463_democrats": 0,
        "committee_464_republicans": 0,
        "committee_464_democrats": 0,
        "committee_465_republicans": 0,
        "committee_465_democrats": 0,
        "committee_466_republicans": 0,
        "committee_466_democrats": 0,
        "committee_467_republicans": 0,
        "committee_467_democrats": 0,
        "committee_468_republicans": 0,
        "committee_468_democrats": 0,
        "committee_469_republicans": 0,
        "committee_469_democrats": 0,
        "committee_470_republicans": 0,
        "committee_470_democrats": 0,
        "committee_471_republicans": 0,
        "committee_471_democrats": 0,
        "committee_472_republicans": 0,
        "committee_472_democrats": 0,
        "committee_473_republicans": 0,
        "committee_473_democrats": 0,
        "committee_474_republicans": 0,
        "committee_474_democrats": 0,
        "committee_475_republicans": 0,
        "committee_475_democrats": 0,
        "committee_476_republicans": 0,
        "committee_476_democrats": 0,
        "committee_477_republicans": 0,
        "committee_477_democrats": 0,
        "committee_478_republicans": 0,
        "committee_478_democrats": 0,
        "committee_479_republicans": 0,
        "committee_479_democrats": 0,
        "committee_480_republicans": 0,
        "committee_480_democrats": 0,
        "committee_481_republicans": 0,
        "committee_481_democrats": 0,
        "committee_482_republicans": 0,
        "committee_482_democrats": 0,
        "committee_483_republicans": 0,
        "committee_483_democrats": 0,
        "committee_484_republicans": 0,
        "committee_484_democrats": 0,
        "committee_485_republicans": 0,
        "committee_485_democrats": 0,
        "committee_486_republicans": 0,
        "committee_486_democrats": 0,
        "committee_487_republicans": 0,
        "committee_487_democrats": 0,
        "committee_488_republicans": 0,
        "committee_488_democrats": 0,
        "committee_489_republicans": 0,
        "committee_489_democrats": 0,
        "committee_490_republicans": 0,
        "committee_490_democrats": 0,
        "committee_491_republicans": 0,
        "committee_491_democrats": 0,
        "committee_492_republicans": 0,
        "committee_492_democrats": 0,
        "committee_493_republicans": 0,
        "committee_493_democrats": 0,
        "committee_494_republicans": 0,
        "committee_494_democrats": 0,
        "committee_495_republicans": 0,
        "committee_495_democrats": 0,
        "committee_496_republicans": 0,
        "committee_496_democrats": 0,
        "committee_497_republicans": 0,
        "committee_497_democrats": 0,
        "committee_498_republicans": 0,
        "committee_498_democrats": 0,
        "committee_499_republicans": 0,
        "committee_499_democrats": 0,
        "committee_500_republicans": 0,
        "committee_500_democrats": 0,
        "committee_501_republicans": 0,
        "committee_501_democrats": 0,
        "committee_502_republicans": 0,
        "committee_502_democrats": 0,
        "committee_503_republicans": 0,
        "committee_503_democrats": 0,
        "committee_504_republicans": 0,
        "committee_504_democrats": 0,
        "committee_505_republicans": 0,
        "committee_505_democrats": 0,
        "committee_506_republicans": 0,
        "committee_506_democrats": 0,
        "committee_507_republicans": 0,
        "committee_507_democrats": 0,
        "committee_508_republicans": 0,
        "committee_508_democrats": 0,
        "committee_509_republicans": 0,
        "committee_509_democrats": 0,
        "committee_510_republicans": 0,
        "committee_510_democrats": 0,
        "committee_511_republicans": 0,
        "committee_511_democrats": 0,
        "committee_512_republicans": 0,
        "committee_512_democrats": 0,
        "committee_513_republicans": 0,
        "committee_513_democrats": 0,
        "committee_514_republicans": 0,
        "committee_514_democrats": 0,
        "committee_515_republicans": 0,
        "committee_515_democrats": 0
    }
    
    #Run this only if leg_sess_data.csv doesn't exist and you need to create the row headers
    if not path.isfile('leg_sess_data.csv'):
        df = pd.DataFrame(columns=list(data.keys()))
        df.to_csv('leg_sess_data.csv', mode='a',index=False)

    #add leg_sess to the data
    data["leg_sess"] = leg_sess

    #get house and senate numbers for the legislature
    #----------------------------------------------
    if leg_sess >= 74:
        URL = 'https://lrl.texas.gov/sessions/memberStatistics.cfm'
        page = requests.get(URL)
        soup = BeautifulSoup(page.content, "html.parser")

        statistics_table = soup.findAll(lambda tag: tag.name=="table")[-(leg_sess - 73)]

        row = statistics_table.find(lambda tag: tag.name == 'td' and tag.text.find('Male') != -1).parent
        data['male_house_members'] = int(re.sub('\D', '', row.contents[3].text))
        data['male_senate_members'] = int(re.sub('\D', '', row.contents[5].text))

        row = statistics_table.find(lambda tag: tag.name == 'td' and tag.text.find('Female') != -1).parent
        data['female_house_members'] = int(re.sub('\D', '', row.contents[3].text))
        data['female_senate_members'] = int(re.sub('\D', '', row.contents[5].text))

        row = statistics_table.find(lambda tag: tag.name == 'td' and tag.text.find('Democrat') != -1).parent
        data['democrat_house_members'] = int(re.sub('\D', '', row.contents[3].text))
        data['democrat_senate_members'] = int(re.sub('\D', '', row.contents[5].text))

        row = statistics_table.find(lambda tag: tag.name == 'td' and tag.text.find('Republican') != -1).parent
        data['republican_house_members'] = int(re.sub('\D', '', row.contents[3].text))
        data['republican_senate_members'] = int(re.sub('\D', '', row.contents[5].text))

        row = statistics_table.find(lambda tag: tag.name == 'td' and tag.text.find('Incumbents') != -1).parent
        data['house_incumbents'] = int(re.sub('\D', '', row.contents[3].text))
        data['senate_incumbents'] = int(re.sub('\D', '', row.contents[5].text))

        row = statistics_table.find(lambda tag: tag.name == 'td' and tag.text.find('Freshmen') != -1).parent
        data['house_freshman'] = int(re.sub('\D', '', row.contents[3].text))
        data['senate_freshman'] = int(re.sub('\D', '', row.contents[5].text))

        row = statistics_table.find(lambda tag: tag.name == 'td' and tag.text.find('Under 30') != -1).parent
        data['house_members_age_under_30'] = int(re.sub('\D', '', row.contents[3].text))
        data['senate_members_age_under_30'] = int(re.sub('\D', '', row.contents[5].text))

        row = statistics_table.find(lambda tag: tag.name == 'td' and (tag.text.find('30 - 39') != -1 or tag.text.find('30-39') != -1)).parent
        data['house_members_age_30_to_39'] = int(re.sub('\D', '', row.contents[3].text))
        data['senate_members_age_30_to_39'] = int(re.sub('\D', '', row.contents[5].text))

        row = statistics_table.find(lambda tag: tag.name == 'td' and (tag.text.find('40 - 49') != -1 or tag.text.find('40-49') != -1)).parent
        data['house_members_age_40_to_49'] = int(re.sub('\D', '', row.contents[3].text))
        data['senate_members_age_40_to_49'] = int(re.sub('\D', '', row.contents[5].text))

        row = statistics_table.find(lambda tag: tag.name == 'td' and (tag.text.find('50 - 59') != -1 or tag.text.find('50-59') != -1)).parent
        data['house_members_age_50_to_59'] = int(re.sub('\D', '', row.contents[3].text))
        data['senate_members_age_50_to_59'] = int(re.sub('\D', '', row.contents[5].text))

        row = statistics_table.find(lambda tag: tag.name == 'td' and (tag.text.find('60 - 69') != -1 or tag.text.find('60-69') != -1)).parent
        data['house_members_age_60_to_69'] = int(re.sub('\D', '', row.contents[3].text))
        data['senate_members_age_60_to_69'] = int(re.sub('\D', '', row.contents[5].text))

        row = statistics_table.find(lambda tag: tag.name == 'td' and tag.text.find('70 and over') != -1).parent
        data['house_members_age_over_70'] = int(re.sub('\D', '', row.contents[3].text))
        data['senate_members_age_over_70'] = int(re.sub('\D', '', row.contents[5].text))


    #Get committee data
    URL = 'https://lrl.texas.gov/committees/cmtes.cfm?from=session&session={}'.format(leg_sess)
    page = requests.get(URL)
    soup = BeautifulSoup(page.content, "html.parser")

    def find_members_party(URL2):
        page2 = requests.get(URL2)
        soup2 = BeautifulSoup(page2.content, "html.parser")
        table2 = soup2.find(name="table")
        party = table2.findAll(name="tr")[5].findAll(name="td")[4].text
        if party.find('Republican') != -1:
            return 'republican'
        elif party.find('Democrat') != -1:
            return 'democrat'
        else:
            return 'other'

    def find_committee_stats(URL2):
        page2 = requests.get(URL2)
        soup2 = BeautifulSoup(page2.content, "html.parser")
        table2 = soup2.find(name="table")

        if not table2:
            return 0, 0

        rows2 = table2.findAll(name='tr')[1].findAll(name='a')
        republican_count = 0
        democrat_count = 0

        for link in rows2:
            party = find_members_party('https://lrl.texas.gov/{}'.format(link.attrs['href']))
            if party == 'republican':
                republican_count+=1
            elif party == 'democrat':
                democrat_count+=1
        
        return republican_count, democrat_count



    table = soup.find(name="table")
    rows = list(map(lambda x: x, table.findAll(lambda tag: tag.name == 'a')))

    for link in rows:
        republican_count, democrat_count = find_committee_stats('https://lrl.texas.gov/committees/{}'.format(link.attrs['href']))
        if 'committee_' + str(committee_to_number[link.text]) + '_republicans' in data:
            data['committee_' + str(committee_to_number[link.text]) + '_republicans'] = republican_count
        if 'committee_' + str(committee_to_number[link.text]) + '_democrats' in data:
            data['committee_' + str(committee_to_number[link.text]) + '_democrats'] = democrat_count

    #print current data
    #-----------------------------
    #print (json.dumps(data, indent=2))


    df = pd.DataFrame(np.array([list(data.values())]), columns=list(data.keys()))
    df.to_csv('leg_sess_data.csv', mode='a',index=False, header=False)

    print(leg_sess, "done")
    leg_sess+=1
